# Generated by Django 6.0.5 on 2026-05-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "merchant_id",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="MerchantID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("password", models.CharField(max_length=255, verbose_name="Password")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="IsActive"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="IsApproved"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="UpdatedAt"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ApprovedAt"
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant",
                "verbose_name_plural": "Merchants",
                "db_table": "merchant",
            },
        ),
    ]
