# Generated by Django 6.0.5 on 2026-05-19 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="phone",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinLengthValidator(11),
                    django.core.validators.MaxLengthValidator(11),
                ],
                verbose_name="PhoneNumber",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
