# Generated by Django 6.0.5 on 2026-05-20 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0002_merchant_phone_alter_merchant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="code",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.MaxLengthValidator(6),
                ],
                verbose_name="OTP",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="expair_code",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ExpairCode"
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="used_code_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="UsedCodeAt"
            ),
        ),
    ]
