# Generated by Django 6.0.5 on 2026-05-20 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0003_merchant_code_merchant_expair_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="OTP must be 6 digits", regex="^\\d{6}$"
                    )
                ],
                verbose_name="OTP",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="phone",
            field=models.CharField(
                default=0,
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 11 digits", regex="^09\\d{9}$"
                    )
                ],
                verbose_name="PhoneNumber",
            ),
        ),
    ]
