# Generated by Django 6.0.5 on 2026-05-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
        ("product", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="merchant.merchant",
                verbose_name="merchant",
            ),
        ),
    ]
