# Generated by Django 6.0.5 on 2026-05-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_pin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pin_code",
            field=models.CharField(verbose_name="Pin Code"),
        ),
    ]
