# Generated by Django 6.0.5 on 2026-05-20 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_pin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pin_code",
            field=models.CharField(
                max_length=4,
                validators=[django.core.validators.RegexValidator(regex="^\\d{4}$")],
                verbose_name="Pin Code",
            ),
        ),
    ]
