# Generated by Django 6.0.5 on 2026-05-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.IntegerField(default=1, verbose_name='CartID'),
            preserve_default=False,
        ),
    ]
