# Generated by Django 6.0.5 on 2026-05-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
    ]
